---
- name: AS3 deployement test
  hosts: localhost
  connection: localhost
  gather_facts: false

  vars:

  vars_files:
  - ../credentials/bigip_vault.yml

  tasks:

  - name: Deploy an AS3 decleration
    uri:
      url: https://51.142.10.142:8443/mgmt/shared/appsvcs/declare
      user: "{{username}}"
      password: "{{password}}"
      method: POST
      body: "{{ lookup('file','as3.json') }}"
      force_basic_auth: true
      status_code: 200
      body_format: json
      validate_certs: false
    register: as3_output

  - name: AS3 output
    debug:
      msg: "{{as3_output.json.declaration.id}}"

...